name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        apt-get update
        apt-get install -y --no-install-recommends git ca-certificates xz-utils
        update-ca-certificates
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix zigler.get_zig latest
        mix docs
    - name: Run Tests
      run: mix test
